# SPDX-FileCopyrightText: Copyright 2026 The OSPS Baseline Authors
# SPDX-License-Identifier: Apache-2.0
---
name: Validate CUE Schemas

on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  validate-catalog:
    name: Validate Catalog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: cmd/go.mod
          check-latest: true
          cache: true

      - name: Setup CUE
        uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1 # v1.0.1
        with:
          version: latest

      - name: Generate Gemara output
        run: |
          go build -C cmd/  -o ../baseline-compiler
          ./baseline-compiler gemara -b baseline > baseline.gemara.yaml

      - name: Validate catalog against CUE schema
        run: cd schema && cue vet -d '#OSPSBaseline' . ../baseline.gemara.yaml

      - name: Validate mapping documents against CUE schema
        run: |
          cd schema
          for f in ../baseline/mappings/*.yaml; do
            echo "vetting $f"
            cue vet -d '#OSPSMapping' . "$f"
          done
